print("calculator".center(20,"-"))
a = float(input("masukan angka\t:"))
b = float(input("masukan angka\t;"))
print("\naritmatic and varibael\n".center(96,"-"))
print("summation".ljust(24))
print(f"{a}+{b}={a+b}")
print("elimination".ljust(35))
print(f"{a}-{b}={a-b}")
print("multiplication".ljust(35))
print(f"{a}*{b}={a*b}")
print("division".ljust(35))
print(f"{a}/{b}={a/b}")
print("multi division".ljust(35))
print(f"{a}//{b}={a//b}")
print("modulus".ljust(35))
print(f'{a}%{b}={int(a % b)}')

